"""Submit: create_tstatamp column

Revision ID: 8c4e132224eb
Revises: e4fe8ef02942
Create Date: 2020-10-18 02:42:30.359476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c4e132224eb'
down_revision = 'e4fe8ef02942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_tstamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submit', schema=None) as batch_op:
        batch_op.drop_column('create_tstamp')

    # ### end Alembic commands ###
